# Generated by Django 3.2.12 on 2022-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_des',
            field=models.CharField(default='', max_length=300),
        ),
    ]
