# Generated by Django 4.0.4 on 2022-06-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
