# Generated by Django 4.0.4 on 2022-06-03 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_time_remove_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
