# Generated by Django 4.0.4 on 2022-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ssno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=300)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
