# Generated by Django 4.0.4 on 2022-06-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0004_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
