# Generated by Django 4.0.4 on 2022-06-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0005_remove_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
