# Generated by Django 4.0.4 on 2022-06-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0006_remove_event_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
