# Generated by Django 4.0.4 on 2022-06-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0010_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
