# Generated by Django 4.0.4 on 2022-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventPlanner', '0011_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ssno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
