# Generated by Django 4.0.4 on 2022-06-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0012_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
