# Generated by Django 4.0.4 on 2022-06-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0013_rename_event_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
