# Generated by Django 4.0.4 on 2022-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0014_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
